### ISSUE TITLE
"3 moderate severity vulnerabilities" can u plz solve this issue as fast as u can 

### ISSUE THREAD

**Issue by NagaprajwalB** [Bilal025/EventoEMS#10]
![Screenshot 2024-11-07 000117](https://github.com/user-attachments/assets/4a1a0665-fd3f-41c4-9eb1-a249ac3ba7dd)

**Comment by TanaySingh02** [comment]
just delete the node modules folder and reinstall it again using npm install in the client folder

**Comment by NagaprajwalB** [comment]
I tried this step many times but it's not working, is their any other ways to solve it ?   

> just delete the node modules folder and reinstall it again using npm install in the client folder
>

**Comment by Callmeharshit** [comment]
Did you find any sloutions regarding this issue?

**Comment by NagaprajwalB** [comment]
> Did you find any sloutions regarding this issue?

NO I tried in many ways, i think there may be difference in the project version and version of the softwares
